# LICENSE PLATE EVALUATION FOR KAGGLE DATASET (Subset)

In [1]:
import pandas as pd
import numpy as np

In [2]:
header = ["Plate"]
dt=pd.read_csv('K_groundtruth.csv',names=header)
dt.dtypes

Plate    object
dtype: object

In [3]:
dt['Plate'].str.split('',expand=True).head(20)

   0  1  2  3  4  5     6     7     8     9     10    11
0      E  4  G  L  E        None  None  None  None  None
1      P  L  8  R  E     C        None  None  None  None
2      D  A  N  5  4     P        None  None  None  None
3      9  A  S  F     None  None  None  None  None  None
4      S  K  5  5  3     A     L        None  None  None
5      A  K  0  0  2     8     1        None  None  None
6      3  1  7  J  9     3     9        None  None  None
7      Z  G  6  8  7     N     L        None  None  None
8      H  R  2  6  B     R     9     0     4     4
9      H  R  2  6  B     P     3     5     4     3
10     M  H  0  1  A     V     8     8     6     6
11     H  9  8  2  F     K     L        None  None  None
12     3  2  5  J  5     2     1        None  None  None
13     K  K  2  3  1     3     L        None  None  None
14     Z  G  8  6  2     N     S        None  None  None
15     Z  G  6  3  4     7     H        None  None  None
16     1  5  L  K  1     0     8     9     8        None
17     A  A  S  H  9     3     8        None  None  None
18     Z  G  4  9  5     Z     R        None  None  None
19     S  K  6  4  6     C     A        None  None  None

In [4]:
header2 = ["Plate"]
drf=pd.read_csv('Ksubset_RF.csv',skip_blank_lines=False,names=header2)
drf.dtypes

Plate    object
dtype: object

In [5]:
drf['Plate'].str.split('',expand=True)

   0  1  2     3     4     5     6     7     8     9     10    11
0      W  E     4     G     L     E        None  None  None  None
1      P  L     B     R     E     C        None  None  None  None
2      U  A     N     S     4     P        None  None  None  None
3      9  A     S     F        None  None  None  None  None  None
4      S  K     L     L     3     A     L        None  None  None
5      L  K     U     U     2     B     1        None  None  None
6      J  J     J     7     J     9     J     9        None  None
7      J  H     H     H     J     N     L        None  None  None
8      J     None  None  None  None  None  None  None  None  None
9      H  R     2     6     B     P     3     L     4     3
10     H  H     U     I     L     V     B     H     6     6
11     H  H     H     2     F     K     L        None  None  None
12     3  2     5     J     L     2     1        None  None  None
13     K  K     2     J     1     J     L        None  None  None
14     J  G     H     H     2     N     S        None  None  None
15     L  Z     G     H     J     A     7     H        None  None
16     1  5     L     K     1     U     8     9     8        None
17     A  A     S     H     9     3     H        None  None  None
18     7  G     4     H     L     7     P        None  None  None
19     S  K     H     A     H     C     A        None  None  None
20     9  B     3     T     9     J     9        None  None  None
21     K  7     4     2     2     S        None  None  None  None
22     S  H     2     H     H     H     7        None  None  None
23     H  U     6     7     H     P     X        None  None  None
24     K  A     A     C     6     8     9        None  None  None
25     9  7     7     K     5     9     3        None  None  None
26     P  G     M     N     I     1     2        None  None  None
27     F  B     R     E     1     8     2        None  None  None
28     K  U     2     2     2     2     A     K        None  None
29     7  G     2     3     2     H     V        None  None  None

# Part 1 - Accuracy of the Entire License Plate

In [6]:
cp = pd.merge(dt, drf, how='inner', on=['Plate']).count()
cp

Plate    4
dtype: int64

In [7]:
missing = dt['Plate'].count() - drf['Plate'].count()
missing

0

In [8]:
fail = 30 - cp - missing
fail

Plate    26
dtype: int64

In [9]:
correct = cp/30
miss = missing/30
fail_detect = fail/30

In [10]:
print ('Correct / Overall Plates -> ' , round(correct, 2).to_string())
print ('Missing / Overall Plates -> ' , round(miss, 2))
print ('Failed Detection / Overall Plates -> ' , round(fail_detect, 2).to_string())

Correct / Overall Plates ->  Plate    0.13
Missing / Overall Plates ->  0.0
Failed Detection / Overall Plates ->  Plate    0.87

The Accuracy of the Entire License Plate

In [11]:
Accuracy = correct * 100
print('Accuracy', round(Accuracy, 2).to_string(), '%')

Accuracy Plate    13.33 %

# Part 2 -> Accuracy of the characters by row for each License Plate

In [12]:
merged = dt.copy()

In [13]:
merged['Plate2'] = drf['Plate']
merged.head(20)

         Plate      Plate2
0        E4GLE      WE4GLE
1       PL8REC      PLBREC
2       DAN54P      UANS4P
3         9ASF        9ASF
4      SK553AL     SKLL3AL
5      AK00281     LKUU2B1
6      317J939    JJJ7J9J9
7      ZG687NL     JHHHJNL
8   HR26BR9044           J
9   HR26BP3543  HR26BP3L43
10  MH01AV8866  HHUILVBH66
11     H982FKL     HHH2FKL
12     325J521     325JL21
13     KK2313L     KK2J1JL
14     ZG862NS     JGHH2NS
15     ZG6347H    LZGHJA7H
16   15LK10898   15LK1U898
17     AASH938     AASH93H
18     ZG495ZR     7G4HL7P
19     SK646CA     SKHAHCA

In [14]:
merged1 = merged['Plate'].str.split('',expand=True)
merged2 = merged['Plate2'].str.split('',expand=True)
m3 = merged1 + merged2
m3.head(20)

   0   1   2    3    4    5    6    7    8    9    10   11
0      EW  4E   G4   LG   EL    E  NaN  NaN  NaN  NaN  NaN
1      PP  LL   8B   RR   EE   CC       NaN  NaN  NaN  NaN
2      DU  AA   NN   5S   44   PP       NaN  NaN  NaN  NaN
3      99  AA   SS   FF       NaN  NaN  NaN  NaN  NaN  NaN
4      SS  KK   5L   5L   33   AA   LL       NaN  NaN  NaN
5      AL  KK   0U   0U   22   8B   11       NaN  NaN  NaN
6      3J  1J   7J   J7   9J   39   9J    9  NaN  NaN  NaN
7      ZJ  GH   6H   8H   7J   NN   LL       NaN  NaN  NaN
8      HJ   R  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9      HH  RR   22   66   BB   PP   33   5L   44   33
10     MH  HH   0U   1I   AL   VV   8B   8H   66   66
11     HH  9H   8H   22   FF   KK   LL       NaN  NaN  NaN
12     33  22   55   JJ   5L   22   11       NaN  NaN  NaN
13     KK  KK   22   3J   11   3J   LL       NaN  NaN  NaN
14     ZJ  GG   8H   6H   22   NN   SS       NaN  NaN  NaN
15     ZL  GZ   6G   3H   4J   7A   H7    H  NaN  NaN  NaN
16     11  55   LL   KK   11   0U   88   99   88       NaN
17     AA  AA   SS   HH   99   33   8H       NaN  NaN  NaN
18     Z7  GG   44   9H   5L   Z7   RP       NaN  NaN  NaN
19     SS  KK   6H   4A   6H   CC   AA       NaN  NaN  NaN

In [15]:
m4=m3.copy()

Calculate how many that are correctly predicted. Example: AA, BB, CC, ...

In [16]:
m4['AA']=(m4 == 'AA').T.sum()
m4['BB']=(m4 == 'BB').T.sum()
m4['CC']=(m4 == 'CC').T.sum()
m4['DD']=(m4 == 'DD').T.sum()
m4['EE']=(m4 == 'EE').T.sum()
m4['FF']=(m4 == 'FF').T.sum()
m4['GG']=(m4 == 'GG').T.sum()
m4['HH']=(m4 == 'HH').T.sum()
m4['II']=(m4 == 'II').T.sum()
m4['JJ']=(m4 == 'JJ').T.sum()
m4['KK']=(m4 == 'KK').T.sum()
m4['LL']=(m4 == 'LL').T.sum()
m4['MM']=(m4 == 'MM').T.sum()
m4['NN']=(m4 == 'NN').T.sum()
m4['OO']=(m4 == 'OO').T.sum()
m4['PP']=(m4 == 'PP').T.sum()
m4['QQ']=(m4 == 'QQ').T.sum()
m4['RR']=(m4 == 'RR').T.sum()
m4['SS']=(m4 == 'SS').T.sum()
m4['TT']=(m4 == 'TT').T.sum()
m4['UU']=(m4 == 'UU').T.sum()
m4['VV']=(m4 == 'VV').T.sum()
m4['WW']=(m4 == 'WW').T.sum()
m4['XX']=(m4 == 'XX').T.sum()
m4['YY']=(m4 == 'YY').T.sum()
m4['ZZ']=(m4 == 'ZZ').T.sum()

m4['00']=(m4 == '00').T.sum()
m4['11']=(m4 == '11').T.sum()
m4['22']=(m4 == '22').T.sum()
m4['33']=(m4 == '33').T.sum()
m4['44']=(m4 == '44').T.sum()
m4['55']=(m4 == '55').T.sum()
m4['66']=(m4 == '66').T.sum()
m4['77']=(m4 == '77').T.sum()
m4['88']=(m4 == '88').T.sum()
m4['99']=(m4 == '99').T.sum()

In [17]:
m4[['AA', 'BB', 'CC', 'DD', 'EE', 'FF', 'GG', 'HH', 'II', 'JJ', 'KK', 'LL', 'MM', 'NN', 'OO', 'PP', 'QQ', 'RR', 'SS', 'TT', 'UU', 'VV', 'WW', 'XX', 'YY', 'ZZ', '00', '11', '22', '33', '44', '55', '66', '77', '88', '99']].head(20)

,AA,BB,CC,DD,EE,FF,GG,HH,II,JJ,...,00,11,22,33,44,55,66,77,88,99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,1,0,0,0,0,0,1,0,0,...,0,0,1,2,1,0,1,0,0,0
10,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,2,0,0,0
11,0,0,0,0,0,1,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,1,...,0,1,2,1,0,1,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
14,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,1,0,0,2,1
17,2,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
18,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
19,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
m4["Correct(TP)"] = m4.sum(axis=1)

C:\Users\JIAYU~1\AppData\Local\Temp/ipykernel_12660/3922289713.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  m4["Correct(TP)"] = m4.sum(axis=1)

In [19]:
m4

,0,1,2,3,4,5,6,7,8,9,...,11,22,33,44,55,66,77,88,99,Correct(TP)
0,,EW,4E,G4,LG,EL,E,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,,PP,LL,8B,RR,EE,CC,,NaN,NaN,...,0,0,0,0,0,0,0,0,0,5
2,,DU,AA,NN,5S,44,PP,,NaN,NaN,...,0,0,0,1,0,0,0,0,0,4
3,,99,AA,SS,FF,,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,1,4
4,,SS,KK,5L,5L,33,AA,LL,,NaN,...,0,0,1,0,0,0,0,0,0,5
5,,AL,KK,0U,0U,22,8B,11,,NaN,...,1,1,0,0,0,0,0,0,0,3
6,,3J,1J,7J,J7,9J,39,9J,9,NaN,...,0,0,0,0,0,0,0,0,0,0
7,,ZJ,GH,6H,8H,7J,NN,LL,,NaN,...,0,0,0,0,0,0,0,0,0,2
8,,HJ,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
9,,HH,RR,22,66,BB,PP,33,5L,44,...,0,1,2,1,0,1,0,0,0,9
10,,MH,HH,0U,1I,AL,VV,8B,8H,66,...,0,0,0,0,0,2,0,0,0,4
11,,HH,9H,8H,22,FF,KK,LL,,NaN,...,0,1,0,0,0,0,0,0,0,5
12,,33,22,55,JJ,5L,22,11,,NaN,...,1,2,1,0,1,0,0,0,0,6
13,,KK,KK,22,3J,11,3J,LL,,NaN,...,1,1,0,0,0,0,0,0,0,5
14,,ZJ,GG,8H,6H,22,NN,SS,,NaN,...,0,1,0,0,0,0,0,0,0,4
15,,ZL,GZ,6G,3H,4J,7A,H7,H,NaN,...,0,0,0,0,0,0,0,0,0,0
16,,11,55,LL,KK,11,0U,88,99,88,...,2,0,0,0,1,0,0,2,1,8
17,,AA,AA,SS,HH,99,33,8H,,NaN,...,0,0,1,0,0,0,0,0,1,6
18,,Z7,GG,44,9H,5L,Z7,RP,,NaN,...,0,0,0,1,0,0,0,0,0,2
19,,SS,KK,6H,4A,6H,CC,AA,,NaN,...,0,0,0,0,0,0,0,0,0,4
20,,99,8B,33,TT,99,3J,99,,NaN,...,0,0,1,0,0,0,0,0,3,5
21,,KK,Z7,44,22,22,SS,,NaN,NaN,...,0,2,0,1,0,0,0,0,0,5
22,,SS,BH,22,6H,8H,BH,Z7,,NaN,...,0,1,0,0,0,0,0,0,0,2
23,,BH,WU,66,77,8H,RP,XX,,NaN,...,0,0,0,0,0,1,1,0,0,3
24,,KK,AA,AA,CC,16,68,89,9,NaN,...,0,0,0,0,0,0,0,0,0,4
25,,99,77,77,KK,55,99,33,,NaN,...,0,0,1,0,1,0,2,0,2,7
26,,PP,GG,MM,NN,1I,11,22,,NaN,...,1,1,0,0,0,0,0,0,0,6
27,,FF,BB,RR,EE,11,88,22,,NaN,...,1,1,0,0,0,0,0,1,0,7
28,,KK,UU,22,22,22,22,AA,KK,,...,0,4,0,0,0,0,0,0,0,8
29,,Z7,GG,22,33,22,8H,VV,,NaN,...,0,2,1,0,0,0,0,0,0,5

In [20]:
dataString = dt.copy()
stringData = dataString.to_string()

In [21]:
dataString["PlateLength"]= dataString['Plate'].str.len()

In [22]:
dataString["Correct(TP)"] = m4["Correct(TP)"]

In [23]:
dataString["Overall"] = dataString['Correct(TP)']/dataString['PlateLength']

In [24]:
dataString["Overall"] = dataString['Overall'].round(2)

In [25]:
dataString

         Plate  PlateLength  Correct(TP)  Overall
0        E4GLE            5            0     0.00
1       PL8REC            6            5     0.83
2       DAN54P            6            4     0.67
3         9ASF            4            4     1.00
4      SK553AL            7            5     0.71
5      AK00281            7            3     0.43
6      317J939            7            0     0.00
7      ZG687NL            7            2     0.29
8   HR26BR9044           10            0     0.00
9   HR26BP3543           10            9     0.90
10  MH01AV8866           10            4     0.40
11     H982FKL            7            5     0.71
12     325J521            7            6     0.86
13     KK2313L            7            5     0.71
14     ZG862NS            7            4     0.57
15     ZG6347H            7            0     0.00
16   15LK10898            9            8     0.89
17     AASH938            7            6     0.86
18     ZG495ZR            7            2     0.29
19     SK646CA            7            4     0.57
20     983T939            7            5     0.71
21      KZ422S            6            5     0.83
22     SB268BZ            7            2     0.29
23     BW678RX            7            3     0.43
24    KAAC1689            8            4     0.50
25     977K593            7            7     1.00
26     PGMN112            7            6     0.86
27     FBRE182            7            7     1.00
28    KU2222AK            8            8     1.00
29     ZG2328V            7            5     0.71

In [26]:
acc = dataString['Overall'].sum()/30*100

The accuracy for the characters

In [27]:
print('Accuracy - > ', acc.round(2), '%')

Accuracy - >  60.07 %

# Part 3 - Precision and Recall

Replace NaN to "-". If the model could not predict, it will return "-"

In [28]:
rp=merged2.replace(np.nan, '-')
gt=merged1.replace(np.nan, '-')

Merge the Groundtruth characters with Prediction characters. Example: MA -> M is Groundtruth, A is predicted. If A- means A is groundtruth, - is the model can't predict

In [29]:
test = gt+rp
test.head(20)

   0   1   2   3   4   5   6   7   8   9   10  11
0      EW  4E  G4  LG  EL   E   -  --  --  --  --
1      PP  LL  8B  RR  EE  CC      --  --  --  --
2      DU  AA  NN  5S  44  PP      --  --  --  --
3      99  AA  SS  FF      --  --  --  --  --  --
4      SS  KK  5L  5L  33  AA  LL      --  --  --
5      AL  KK  0U  0U  22  8B  11      --  --  --
6      3J  1J  7J  J7  9J  39  9J   9   -  --  --
7      ZJ  GH  6H  8H  7J  NN  LL      --  --  --
8      HJ   R  2-  6-  B-  R-  9-  0-  4-  4-   -
9      HH  RR  22  66  BB  PP  33  5L  44  33
10     MH  HH  0U  1I  AL  VV  8B  8H  66  66
11     HH  9H  8H  22  FF  KK  LL      --  --  --
12     33  22  55  JJ  5L  22  11      --  --  --
13     KK  KK  22  3J  11  3J  LL      --  --  --
14     ZJ  GG  8H  6H  22  NN  SS      --  --  --
15     ZL  GZ  6G  3H  4J  7A  H7   H   -  --  --
16     11  55  LL  KK  11  0U  88  99  88      --
17     AA  AA  SS  HH  99  33  8H      --  --  --
18     Z7  GG  44  9H  5L  Z7  RP      --  --  --
19     SS  KK  6H  4A  6H  CC  AA      --  --  --

In [30]:
test1=test.replace(np.nan, '-')
test1

   0   1   2   3   4   5   6   7   8   9   10  11
0      EW  4E  G4  LG  EL   E   -  --  --  --  --
1      PP  LL  8B  RR  EE  CC      --  --  --  --
2      DU  AA  NN  5S  44  PP      --  --  --  --
3      99  AA  SS  FF      --  --  --  --  --  --
4      SS  KK  5L  5L  33  AA  LL      --  --  --
5      AL  KK  0U  0U  22  8B  11      --  --  --
6      3J  1J  7J  J7  9J  39  9J   9   -  --  --
7      ZJ  GH  6H  8H  7J  NN  LL      --  --  --
8      HJ   R  2-  6-  B-  R-  9-  0-  4-  4-   -
9      HH  RR  22  66  BB  PP  33  5L  44  33
10     MH  HH  0U  1I  AL  VV  8B  8H  66  66
11     HH  9H  8H  22  FF  KK  LL      --  --  --
12     33  22  55  JJ  5L  22  11      --  --  --
13     KK  KK  22  3J  11  3J  LL      --  --  --
14     ZJ  GG  8H  6H  22  NN  SS      --  --  --
15     ZL  GZ  6G  3H  4J  7A  H7   H   -  --  --
16     11  55  LL  KK  11  0U  88  99  88      --
17     AA  AA  SS  HH  99  33  8H      --  --  --
18     Z7  GG  44  9H  5L  Z7  RP      --  --  --
19     SS  KK  6H  4A  6H  CC  AA      --  --  --
20     99  8B  33  TT  99  3J  99      --  --  --
21     KK  Z7  44  22  22  SS      --  --  --  --
22     SS  BH  22  6H  8H  BH  Z7      --  --  --
23     BH  WU  66  77  8H  RP  XX      --  --  --
24     KK  AA  AA  CC  16  68  89   9   -  --  --
25     99  77  77  KK  55  99  33      --  --  --
26     PP  GG  MM  NN  1I  11  22      --  --  --
27     FF  BB  RR  EE  11  88  22      --  --  --
28     KK  UU  22  22  22  22  AA  KK      --  --
29     Z7  GG  22  33  22  8H  VV      --  --  --

In [31]:
test1['AA']=(test1 == 'AA').T.sum()
test1['BB']=(test1 == 'BB').T.sum()
test1['CC']=(test1 == 'CC').T.sum()
test1['DD']=(test1 == 'DD').T.sum()
test1['EE']=(test1 == 'EE').T.sum()
test1['FF']=(test1 == 'FF').T.sum()
test1['GG']=(test1 == 'GG').T.sum()
test1['HH']=(test1 == 'HH').T.sum()
test1['II']=(test1 == 'II').T.sum()
test1['JJ']=(test1 == 'JJ').T.sum()
test1['KK']=(test1 == 'KK').T.sum()
test1['LL']=(test1 == 'LL').T.sum()
test1['MM']=(test1 == 'MM').T.sum()
test1['NN']=(test1 == 'NN').T.sum()
test1['OO']=(test1 == 'OO').T.sum()
test1['PP']=(test1 == 'PP').T.sum()
test1['QQ']=(test1 == 'QQ').T.sum()
test1['RR']=(test1 == 'RR').T.sum()
test1['SS']=(test1 == 'SS').T.sum()
test1['TT']=(test1 == 'TT').T.sum()
test1['UU']=(test1 == 'UU').T.sum()
test1['VV']=(test1 == 'VV').T.sum()
test1['WW']=(test1 == 'WW').T.sum()
test1['XX']=(test1 == 'XX').T.sum()
test1['YY']=(test1 == 'YY').T.sum()
test1['ZZ']=(test1 == 'ZZ').T.sum()

test1['00']=(test1 == '00').T.sum()
test1['11']=(test1 == '11').T.sum()
test1['22']=(test1 == '22').T.sum()
test1['33']=(test1 == '33').T.sum()
test1['44']=(test1 == '44').T.sum()
test1['55']=(test1 == '55').T.sum()
test1['66']=(test1 == '66').T.sum()
test1['77']=(test1 == '77').T.sum()
test1['88']=(test1 == '88').T.sum()
test1['99']=(test1 == '99').T.sum()

In [32]:
test1["Sum(TP)"] = test1.sum(axis=1)

C:\Users\JIAYU~1\AppData\Local\Temp/ipykernel_12660/2875601810.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  test1["Sum(TP)"] = test1.sum(axis=1)

In [33]:
test2 = test.copy()

Calculate how many that cannot be predicted. Example: A-, B-, C-, ...

In [34]:
test2['A-']=(test2 == 'A-').T.sum()
test2['B-']=(test2 == 'B-').T.sum()
test2['C-']=(test2 == 'C-').T.sum()
test2['D-']=(test2 == 'D-').T.sum()
test2['E-']=(test2 == 'E-').T.sum()
test2['F-']=(test2 == 'F-').T.sum()
test2['G-']=(test2 == 'G-').T.sum()
test2['H-']=(test2 == 'H-').T.sum()
test2['I-']=(test2 == 'I-').T.sum()
test2['J-']=(test2 == 'J-').T.sum()
test2['K-']=(test2 == 'K-').T.sum()
test2['L-']=(test2 == 'L-').T.sum()
test2['M-']=(test2 == 'M-').T.sum()
test2['N-']=(test2 == 'N-').T.sum()
test2['O-']=(test2 == 'O-').T.sum()
test2['P-']=(test2 == 'P-').T.sum()
test2['Q-']=(test2 == 'Q-').T.sum()
test2['R-']=(test2 == 'R-').T.sum()
test2['S-']=(test2 == 'S-').T.sum()
test2['T-']=(test2 == 'T-').T.sum()
test2['U-']=(test2 == 'U-').T.sum()
test2['V-']=(test2 == 'V-').T.sum()
test2['W-']=(test2 == 'W-').T.sum()
test2['X-']=(test2 == 'X-').T.sum()
test2['Y-']=(test2 == 'Y-').T.sum()
test2['Z-']=(test2 == 'Z-').T.sum()

test2['0-']=(test2 == '0-').T.sum()
test2['1-']=(test2 == '1-').T.sum()
test2['2-']=(test2 == '2-').T.sum()
test2['3-']=(test2 == '3-').T.sum()
test2['4-']=(test2 == '4-').T.sum()
test2['5-']=(test2 == '5-').T.sum()
test2['6-']=(test2 == '6-').T.sum()
test2['7-']=(test2 == '7-').T.sum()
test2['8-']=(test2 == '8-').T.sum()
test2['9-']=(test2 == '9-').T.sum()

In [35]:
test2["Sum(FN)"] = test2.sum(axis=1)
test2

C:\Users\JIAYU~1\AppData\Local\Temp/ipykernel_12660/1776673086.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  test2["Sum(FN)"] = test2.sum(axis=1)

,0,1,2,3,4,5,6,7,8,9,...,1-,2-,3-,4-,5-,6-,7-,8-,9-,Sum(FN)
0,,EW,4E,G4,LG,EL,E,-,--,--,...,0,0,0,0,0,0,0,0,0,0
1,,PP,LL,8B,RR,EE,CC,,--,--,...,0,0,0,0,0,0,0,0,0,0
2,,DU,AA,NN,5S,44,PP,,--,--,...,0,0,0,0,0,0,0,0,0,0
3,,99,AA,SS,FF,,--,--,--,--,...,0,0,0,0,0,0,0,0,0,0
4,,SS,KK,5L,5L,33,AA,LL,,--,...,0,0,0,0,0,0,0,0,0,0
5,,AL,KK,0U,0U,22,8B,11,,--,...,0,0,0,0,0,0,0,0,0,0
6,,3J,1J,7J,J7,9J,39,9J,9,-,...,0,0,0,0,0,0,0,0,0,0
7,,ZJ,GH,6H,8H,7J,NN,LL,,--,...,0,0,0,0,0,0,0,0,0,0
8,,HJ,R,2-,6-,B-,R-,9-,0-,4-,...,0,1,0,2,0,1,0,0,1,8
9,,HH,RR,22,66,BB,PP,33,5L,44,...,0,0,0,0,0,0,0,0,0,0
10,,MH,HH,0U,1I,AL,VV,8B,8H,66,...,0,0,0,0,0,0,0,0,0,0
11,,HH,9H,8H,22,FF,KK,LL,,--,...,0,0,0,0,0,0,0,0,0,0
12,,33,22,55,JJ,5L,22,11,,--,...,0,0,0,0,0,0,0,0,0,0
13,,KK,KK,22,3J,11,3J,LL,,--,...,0,0,0,0,0,0,0,0,0,0
14,,ZJ,GG,8H,6H,22,NN,SS,,--,...,0,0,0,0,0,0,0,0,0,0
15,,ZL,GZ,6G,3H,4J,7A,H7,H,-,...,0,0,0,0,0,0,0,0,0,0
16,,11,55,LL,KK,11,0U,88,99,88,...,0,0,0,0,0,0,0,0,0,0
17,,AA,AA,SS,HH,99,33,8H,,--,...,0,0,0,0,0,0,0,0,0,0
18,,Z7,GG,44,9H,5L,Z7,RP,,--,...,0,0,0,0,0,0,0,0,0,0
19,,SS,KK,6H,4A,6H,CC,AA,,--,...,0,0,0,0,0,0,0,0,0,0
20,,99,8B,33,TT,99,3J,99,,--,...,0,0,0,0,0,0,0,0,0,0
21,,KK,Z7,44,22,22,SS,,--,--,...,0,0,0,0,0,0,0,0,0,0
22,,SS,BH,22,6H,8H,BH,Z7,,--,...,0,0,0,0,0,0,0,0,0,0
23,,BH,WU,66,77,8H,RP,XX,,--,...,0,0,0,0,0,0,0,0,0,0
24,,KK,AA,AA,CC,16,68,89,9,-,...,0,0,0,0,0,0,0,0,0,0
25,,99,77,77,KK,55,99,33,,--,...,0,0,0,0,0,0,0,0,0,0
26,,PP,GG,MM,NN,1I,11,22,,--,...,0,0,0,0,0,0,0,0,0,0
27,,FF,BB,RR,EE,11,88,22,,--,...,0,0,0,0,0,0,0,0,0,0
28,,KK,UU,22,22,22,22,AA,KK,,...,0,0,0,0,0,0,0,0,0,0
29,,Z7,GG,22,33,22,8H,VV,,--,...,0,0,0,0,0,0,0,0,0,0

In [36]:
test3 = dt.copy()
test3['Model Data'] = merged['Plate2']
test3['PlateLength'] = dataString["PlateLength"]
test3['Correct(TP)'] = test1['Sum(TP)']
test3['Missing(FN)'] = test2['Sum(FN)']
test3['Incorrect(FP)'] = test3['PlateLength'] - test3['Correct(TP)'] - test3['Missing(FN)']

In [37]:
test3

,Plate,Model Data,PlateLength,Correct(TP),Missing(FN),Incorrect(FP)
0,E4GLE,WE4GLE,5,0,0,5
1,PL8REC,PLBREC,6,5,0,1
2,DAN54P,UANS4P,6,4,0,2
3,9ASF,9ASF,4,4,0,0
4,SK553AL,SKLL3AL,7,5,0,2
5,AK00281,LKUU2B1,7,3,0,4
6,317J939,JJJ7J9J9,7,0,0,7
7,ZG687NL,JHHHJNL,7,2,0,5
8,HR26BR9044,J,10,0,8,2
9,HR26BP3543,HR26BP3L43,10,9,0,1
10,MH01AV8866,HHUILVBH66,10,4,0,6
11,H982FKL,HHH2FKL,7,5,0,2
12,325J521,325JL21,7,6,0,1
13,KK2313L,KK2J1JL,7,5,0,2
14,ZG862NS,JGHH2NS,7,4,0,3
15,ZG6347H,LZGHJA7H,7,0,0,7
16,15LK10898,15LK1U898,9,8,0,1
17,AASH938,AASH93H,7,6,0,1
18,ZG495ZR,7G4HL7P,7,2,0,5
19,SK646CA,SKHAHCA,7,4,0,3
20,983T939,9B3T9J9,7,5,0,2
21,KZ422S,K7422S,6,5,0,1
22,SB268BZ,SH2HHH7,7,2,0,5
23,BW678RX,HU67HPX,7,3,0,4
24,KAAC1689,KAAC689,8,4,0,4
25,977K593,977K593,7,7,0,0
26,PGMN112,PGMNI12,7,6,0,1
27,FBRE182,FBRE182,7,7,0,0
28,KU2222AK,KU2222AK,8,8,0,0
29,ZG2328V,7G232HV,7,5,0,2

In [38]:
results = test3.copy()
results['Recall'] = results['Correct(TP)'] / (results['Correct(TP)'] + results['Missing(FN)'])
results['Precision'] = results['Correct(TP)'] / (results['Correct(TP)'] + results['Incorrect(FP)'])
results

,Plate,Model Data,PlateLength,Correct(TP),Missing(FN),Incorrect(FP),Recall,Precision
0,E4GLE,WE4GLE,5,0,0,5,NaN,0.000000
1,PL8REC,PLBREC,6,5,0,1,1.0,0.833333
2,DAN54P,UANS4P,6,4,0,2,1.0,0.666667
3,9ASF,9ASF,4,4,0,0,1.0,1.000000
4,SK553AL,SKLL3AL,7,5,0,2,1.0,0.714286
5,AK00281,LKUU2B1,7,3,0,4,1.0,0.428571
6,317J939,JJJ7J9J9,7,0,0,7,NaN,0.000000
7,ZG687NL,JHHHJNL,7,2,0,5,1.0,0.285714
8,HR26BR9044,J,10,0,8,2,0.0,0.000000
9,HR26BP3543,HR26BP3L43,10,9,0,1,1.0,0.900000
10,MH01AV8866,HHUILVBH66,10,4,0,6,1.0,0.400000
11,H982FKL,HHH2FKL,7,5,0,2,1.0,0.714286
12,325J521,325JL21,7,6,0,1,1.0,0.857143
13,KK2313L,KK2J1JL,7,5,0,2,1.0,0.714286
14,ZG862NS,JGHH2NS,7,4,0,3,1.0,0.571429
15,ZG6347H,LZGHJA7H,7,0,0,7,NaN,0.000000
16,15LK10898,15LK1U898,9,8,0,1,1.0,0.888889
17,AASH938,AASH93H,7,6,0,1,1.0,0.857143
18,ZG495ZR,7G4HL7P,7,2,0,5,1.0,0.285714
19,SK646CA,SKHAHCA,7,4,0,3,1.0,0.571429
20,983T939,9B3T9J9,7,5,0,2,1.0,0.714286
21,KZ422S,K7422S,6,5,0,1,1.0,0.833333
22,SB268BZ,SH2HHH7,7,2,0,5,1.0,0.285714
23,BW678RX,HU67HPX,7,3,0,4,1.0,0.428571
24,KAAC1689,KAAC689,8,4,0,4,1.0,0.500000
25,977K593,977K593,7,7,0,0,1.0,1.000000
26,PGMN112,PGMNI12,7,6,0,1,1.0,0.857143
27,FBRE182,FBRE182,7,7,0,0,1.0,1.000000
28,KU2222AK,KU2222AK,8,8,0,0,1.0,1.000000
29,ZG2328V,7G232HV,7,5,0,2,1.0,0.714286

In [39]:
print('Precision - > ', (results['Precision'].sum() / 30 * 100).round(2), '%')
print('Recall - > ', (results['Recall'].sum() / 30 * 100).round(2), '%')

Precision - >  60.07 %
Recall - >  86.67 %